# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOSInputTesting' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'SZTextView'
pod 'JVFloatLabeledTextField'
pod 'RSKGrowingTextView'
pod 'RSKPlaceholderTextView'
pod "SlackTextViewController"
pod 'MBAutoGrowingTextView', '~> 0.1.0'
end

target 'iOSInputTestingTests' do

end

target 'iOSInputTestingUITests' do

end
